WIP: Basic structure for showcasing community contributions
datamol-io/molfeat pull request #59
Opened 2023-05-27 18:15 UTC by cwognum

Checklist:

- [X] Was this PR discussed in a issue? It is recommended to first discuss a new feature and let the community know whether you are planning or have started working on it before opening a PR.
- [ ] Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate).
- [X] Update the API documentation if a new function is added or an existing one is deleted.
- [ ] Added a `news` entry.
  - _copy `news/TEMPLATE.rst` to `news/my-feature-or-branch.rst`) and edit it._

---

ping @maclandrol. I proposed a basic structure so we can discuss! What do you think?

2023-05-27 18:17 UTC, cwognum commented
For now, I was thinking of having a table with a row per contribution. This will not scale, but is a sensible solution for the short-term.

2023-05-27 21:28 UTC, maclandrol commented on docs/community/get_involved.md
> +- :star: **Star** the repository on Github
Add answering questions

2023-05-27 21:37 UTC, maclandrol requested changes

2023-05-27 21:37 UTC, maclandrol commented on docs/community/get_involved.md
> +`molfeat` is an initiative that originated in the [M2D2 community](m2d2.io). To orchestrate these efforts the `#molfeat` channel
Instead, the molfeat community is part of the m2d2 community

2023-05-27 21:37 UTC, maclandrol commented on docs/developers/contribute.md
> +    Visit [Community Contribitons](../community/contributions.md) to learn more!s
There is a typo at the end.

2023-05-27 21:37 UTC, maclandrol commented on docs/developers/contribute.md
> +- :star: **Star** the repository on Github
This seems like a duplicate of the *ways to contribute section* below. Would likely make sense to pull that section up here and/or rephrase both a bit

2023-05-27 21:37 UTC, maclandrol commented on README.md
> +## Contribute and Community
Create subsections  maybe ?  Or just contribute is enough

2023-05-27 21:37 UTC, maclandrol commented on README.md
> +To learn more about the community that is behind molfeat, please see [community](docs/community/).
Community and ecosystem of tools ? Maybe in community we can say things like if you like molfeat, you will like datamol and xyz ?

2023-05-27 21:37 UTC, maclandrol commented on docs/community/contributions.md
> +Made with [contrib.rocks](https://contrib.rocks).
You can remove the contrib rocks part, it's fine.

2023-05-27 21:37 UTC, maclandrol commented on docs/community/contributions.md
> +## Tutorials
I like the split

2023-05-27 21:39 UTC, maclandrol commented
> For now, I was thinking of having a table with a row per contribution that links to an external page (e.g. Github of a plugin, blog post, etc.). Or would you prefer copying as much as possible over to molfeat instead of having a link?

No, the table is perfect. We can also add some links or some badges in the original tutorials too.

2023-05-27 21:39 UTC, maclandrol commented
Also ping @zhu0619

2023-05-28 03:25 UTC, cwognum commented
@maclandrol I addressed your comments! The community contributions page probably still needs some context descriptions, but I'll do those later. In the meantime, could you add the IPU badges? I cannot see the raw README and thus cannot copy the IPU badge (I saw you edited the description, so you probably can?).

2023-05-28 18:57 UTC, cwognum commented
**Reference in existing documentation:**

![image](https://github.com/datamol-io/molfeat/assets/28000055/901cbe66-acc5-4a71-884c-ca5a6d8d7fcf)

**New community contributions table**

![image](https://github.com/datamol-io/molfeat/assets/28000055/4d947cdc-cd9e-4d19-85c2-f069f4ece84e)

2023-05-28 19:08 UTC, maclandrol approved these changes
LGTM, thanks @cwognum. 
Can be merged !

2023-05-28 19:18 UTC, merged